
export const enTranslations = {
  common: {
    welcome: "Welcome",
    loading: "Loading...",
    continue: "Continue",
  },
  nav: {
    features: "Features",
    about: "About",
    community: "Community",
    support: "Support",
    signIn: "Sign In",
    dashboard: "Dashboard",
    settings: "Settings",
  },
  dashboard: {
    welcome: "Welcome to Your Farm Dashboard",
    subtitle: "Monitor your crop health and environmental conditions",
    overview: "Overview",
    cropHealth: "Crop Health",
    soilCondition: "Soil Condition",
    weatherForecast: "Weather Forecast",
    alerts: "Alerts",
    metrics: "Metrics",
    nitrogen: "Nitrogen",
    phosphorus: "Phosphorus",
    potassium: "Potassium",
    moisture: "Moisture",
    temperature: "Temperature",
    humidity: "Humidity",
    recentActivity: "Recent Activity",
    todayAt: "Today at",
    viewAll: "View All",
    seedingComplete: "Seeding completed for Plot A2",
    irrigationScheduled: "Irrigation scheduled for tomorrow",
    fertilizationComplete: "Fertilization completed",
    recommendations: "Recommendations",
    cropProgress: "Crop Progress",
    daysToHarvest: "Days to Harvest",
    growth: "Growth",
    health: "Health",
    goodCondition: "Good condition",
    moderateRisk: "Moderate risk",
    highRisk: "High risk",
    weatherToday: "Weather Today",
    rainfall: "Rainfall",
    sunlight: "Sunlight",
  },
  login: {
    subtitle: "Farmer Management System",
    username: "Username",
    usernamePlaceholder: "Enter your username",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    loginButton: "Sign In",
    loggingIn: "Signing in...",
    noAccount: "Don't have an account?",
    register: "Register now",
    kisanNote: "Kisan Login",
    kisanMessage: "Use your Kisan ID and password provided by your local agricultural department.",
    successTitle: "Login Successful",
    successMessage: "Welcome to your farm dashboard!",
    errorTitle: "Login Failed",
    errorMessage: "Please check your username and password.",
    rightsReserved: "All rights reserved."
  }
};
