
export const taTranslations = {
  common: {
    welcome: "வரவேற்கிறோம்",
    loading: "ஏற்றுகிறது...",
    continue: "தொடரவும்",
  },
  nav: {
    features: "அம்சங்கள்",
    about: "பற்றி",
    community: "சமூகம்",
    support: "ஆதரவு",
    signIn: "உள்நுழைக",
    dashboard: "டாஷ்போர்டு",
    settings: "அமைப்புகள்",
  },
  dashboard: {
    welcome: "உங்கள் விவசாய டாஷ்போர்டுக்கு வரவேற்கிறோம்",
    subtitle: "உங்கள் பயிர் ஆரோக்கியம் மற்றும் சுற்றுச்சூழல் நிலைமைகளை கண்காணிக்கவும்",
    overview: "கண்ணோட்டம்",
    cropHealth: "பயிர் ஆரோக்கியம்",
    soilCondition: "மண் நிலைமை",
    weatherForecast: "வானிலை முன்னறிவிப்பு",
    alerts: "எச்சரிக்கைகள்",
    metrics: "அளவீடுகள்",
    nitrogen: "நைட்ரஜன்",
    phosphorus: "பாஸ்பரஸ்",
    potassium: "பொட்டாசியம்",
    moisture: "ஈரப்பதம்",
    temperature: "வெப்பநிலை",
    humidity: "ஈரப்பதம்",
    recentActivity: "சமீபத்திய செயல்பாடு",
    todayAt: "இன்று",
    viewAll: "அனைத்தையும் காண்க",
    seedingComplete: "ப்ளாட் A2க்கான விதைப்பு முடிந்தது",
    irrigationScheduled: "நாளை நீர்ப்பாசனம் திட்டமிடப்பட்டுள்ளது",
    fertilizationComplete: "உரமிடுதல் நிறைவடைந்தது",
    recommendations: "பரிந்துரைகள்",
    cropProgress: "பயிர் முன்னேற்றம்",
    daysToHarvest: "அறுவடைக்கான நாட்கள்",
    growth: "வளர்ச்சி",
    health: "ஆரோக்கியம்",
    goodCondition: "நல்ல நிலைமை",
    moderateRisk: "மிதமான ஆபத்து",
    highRisk: "அதிக ஆபத்து",
    weatherToday: "இன்றைய வானிலை",
    rainfall: "மழைப்பொழிவு",
    sunlight: "சூரிய ஒளி",
  },
  login: {
    subtitle: "விவசாயி மேலாண்மை அமைப்பு",
    username: "பயனர்பெயர்",
    usernamePlaceholder: "உங்கள் பயனர்பெயரை உள்ளிடவும்",
    password: "கடவுச்சொல்",
    passwordPlaceholder: "உங்கள் கடவுச்சொல்லை உள்ளிடவும்",
    rememberMe: "என்னை நினைவில் வைத்துக்கொள்",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
    loginButton: "உள்நுழைக",
    loggingIn: "உள்நுழைகிறது...",
    noAccount: "கணக்கு இல்லையா?",
    register: "இப்போது பதிவு செய்யுங்கள்",
    kisanNote: "கிசான் உள்நுழைவு",
    kisanMessage: "உங்கள் உள்ளூர் விவசாயத் துறையால் வழங்கப்பட்ட கிசான் ஐடி மற்றும் கடவுச்சொல்லைப் பயன்படுத்தவும்.",
    successTitle: "உள்நுழைவு வெற்றிகரமானது",
    successMessage: "உங்கள் விவசாய டாஷ்போர்டுக்கு வரவேற்கிறோம்!",
    errorTitle: "உள்நுழைவு தோல்வி",
    errorMessage: "தயவுசெய்து உங்கள் பயனர்பெயர் மற்றும் கடவுச்சொல்லை சரிபார்க்கவும்.",
    rightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை."
  }
};
